config/routes.rb
Rails.application.routes.draw do

  resources :blog
  resources :products
  root 'welcome#index'
  # get 'welcome/index'
  # get 'welcome', to: 'welcome#index'
  get 'welcome/index', to: 'welcome#index', as: 'welcome'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/contact_us', to: 'welcome#contact_us'
  get 'welcome/prices', to: 'welcome#prices'

  # get 'blog/index'
  # get 'blog/new'
  # get 'blog/show'
  # get 'blog/edit'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/city.rb
class City < ApplicationRecord
  validates :name, :country,  presence: true
  validates :name, length: {minimum: 10}

  has_many :houses
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :user
  belongs_to :city
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :user
end


# ### ANTES
# Post.create(title: "titulo")
# Post.create!(title: "titulo")
#
# ### DURANTE
# post = Post.new(title: "")
# Post.save
# Post.save!
#
# ### DESPUES
# post = Post.find(1)
# post.update(title: "")
# post.update!(title: "")
#
# post = Post.find(2)
# post.valid? FALSE
# post.invalid? TRUE

app/models/product.rb
class Product < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses

end

app/models/user.rb
class User < ApplicationRecord
#  validates :email, format: {width}
#  validates :phones, numericality: true
#  validates :phones, numericality: {only_integer: true}
#  validates :phones, numericality: {greater_than_or_equal_to: 5 }, presence: true
  validates :phones, presence: true, length: {minimum: 10}
  has_many :houses
  has_many :posts
  has_many :notes
end



# ### ANTES
# Post.create(title: "titulo")
# Post.create!(title: "titulo")
#
# ### DURANTE
# post = Post.new(title: "")
# Post.save
# Post.save!
#
# ### DESPUES
# post = Post.find(1)
# post.update(title: "")
# post.update!(title: "")
#
# post = Post.find(2)
# post.valid? FALSE
# post.invalid? TRUE

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
    @blogs = Blog.all

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end

  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_index_path, notice: "Blog guardado exitosamente"
      # flash[:notice] = "Blog guardado exitosamente"
    else
      flash[:alert] = "Post no guardado"
      render :new
    end
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to blog_index_path
    else
      render :edit
    end
  end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy

    redirect_to blog_index_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :content)
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "Mi nombre es"
  end

  def about
    redirect_to welcome_prices_path
  end

  def contact_us

  end

  def prices

  end

  # Vistas/metodos/acciones
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/edit.html.erb
<%= form_for @blog, url: blog_path(@blog), method: :put do |f|%>
<div>
  <%= f.label :Title %>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :Content %>
  <%= f.text_area :content %>
</div>
<div>
  <%= f.submit %>
</div>
<%end%>

app/views/blog/index.html.erb
<h1 align="center"> Blogs </h1>

<%= link_to "Create new Post", new_blog_path%>

<br>

<table align="center">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
    </tr>
  </thead>
  <body>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to "Show", blog_path(blog.id)%></td>
        <td><%= link_to "Edit", edit_blog_path(blog.id)%></td>
        <td><%= link_to "Delete", blog_path(blog.id), method: :delete, data: {confirm:"Esta seguro de eliminar"}%></td>
      </tr>
    <%end%>
  </body>
</table>






<!-- <p>blog desde index</p>


<!-- Header
     Partial / Helper / componente
-->
  <%# <%= #render 'blog/partials/header' %>

<!--Lista de articulos-->

<!-- <a href="welcome/contact_us" class="link-to-contact">Contactanos</a> -->

<%# <%= #link_to("Contactanos", welcome_contact_us_path, class:"link-to-contact", id: "id-css") %>

<%# <%= #link_to("Prices", welcome_prices_url) %>

<!-- Barra lateral -->

app/views/blog/new.html.erb
<!-- <h1>Formulario desde new</h1>

<form class="" action="index.html" method="post">
  <input type="text" name="" value="">
  <input type="submit" name="" value="">
</form> -->

<%= form_for @blog, url: blog_index_path, method: :post do |f| %>
  <div>
    <%= f.label :Title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :Content %>
    <%= f.text_area :content %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<%end%>

app/views/blog/partials/_header.html.erb
Mis 80 lineas de codigo

app/views/blog/show.html.erb
<h1> Detalles del Blog <%= @blog.id  %> </h1>

<div> Title <%= @blog.title %></div>
<div> Content <%= @blog.content %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/about.erb
<h1>About</h1>

<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  Officia rerum animi, perspiciatis fugit obcaecati quisquam
  quod molestiae deleniti nam quo nulla ullam repellendus,
  ab sequi amet cum ad aut dolore.

  Lorem ipsum dolor sit amet, consectetur adipisicing elit.
  Officia rerum animi, perspiciatis fugit obcaecati quisquam
  quod molestiae deleniti nam quo nulla ullam repellendus,
  ab sequi amet cum ad aut dolore.
</p>

app/views/welcome/contact_us.erb
<h1>contact Us</h1>

<address class="">
  Address: ____________
</address>
<div>Phone: ___________</div>

app/views/welcome/index.html.erb
<%= @name %>

app/views/welcome/prices.erb
<h1>Our Prices</h1>

<ul>
  <li>Basic: $</li>
  <li>Mediem: $</li>
  <li>Advanced: $</li>

</ul>